# Generated by Django 5.0.6 on 2024-06-05 02:33

import vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_vendor_code_historicalvendorperformance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, default=vendors.models.generate_po_number, max_length=50, unique=True),
        ),
    ]
