# Generated by Django 5.0.6 on 2024-06-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_purchaseorder_delivered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='average_response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='fulfillment_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalvendorperformance',
            name='quality_rating_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
